//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankCardsProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class masterCard
    {
        public int id { get; set; }
        public string cardType { get; set; }
        public Nullable<int> cardNumber { get; set; }
        public Nullable<int> cardCharges { get; set; }
        public Nullable<int> cardLimit { get; set; }
    }
}
